name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: IHOJOSE - Inteligencia Artificial
        uses: actions/checkout@v3.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build NX Angular
        run: npm run deploy

      - name: Deploy Static
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.UMB_DEPLOY_KEY }}
          publish_dir: dist
